/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jonatanValenDAT250Exp1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void testInchesToFeetConversion() {
        double result = App.convertUnit(12, "in", "ft");
        assertEquals(1, result, 0.001); // Tolerating small error
    }

    @Test
    public void testFeetToMilesConversion() {
        double result = App.convertUnit(5280, "ft", "mi");
        assertEquals(1, result, 0.001);
    }
}
